/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single bank record in the Africa Bank Data dataset
 */
export interface Bank {
  /**
   * Full legal name of the bank
   */
  name: string;
  /**
   * Country-specific bank code (format varies by country)
   */
  code: string;
  /**
   * URL-safe lowercase identifier, unique within a country
   */
  slug: string;
  /**
   * Abbreviated display name used in space-constrained UIs
   */
  short_name: string;
  /**
   * Institutional classification of the bank
   */
  type: "commercial" | "microfinance" | "development" | "mortgage";
  /**
   * Official bank website URL
   */
  website?: string;
  /**
   * Public customer support email address
   */
  support_email?: string;
  /**
   * USSD shortcode for mobile banking (e.g. *901#)
   */
  ussd?: string;
  /**
   * Alternative names or common misspellings used to match the bank
   */
  aliases?: string[];
}
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Country-level metadata for a supported country in the Africa Bank Data dataset
 */
export interface CountryMetadata {
  /**
   * ISO 3166-1 alpha-2 country code
   */
  country: string;
  /**
   * Full English name of the country
   */
  country_name: string;
  /**
   * ISO 4217 currency code (e.g. NGN, KES)
   */
  currency: string;
  /**
   * Name of the country's central bank
   */
  central_bank: string;
  /**
   * Date the data was last reviewed (YYYY-MM-DD)
   */
  last_updated: string;
}
